- name: install jave sdk  
  hosts: webserver                                  
  become: true                                       
  vars_files:
    - vars.yml
    
  tasks: 

    - name: Update and upgrade all packages to the latest version
      apt:
        update_cache: true
        upgrade: yes
        # So it's good to include if you don't want to update the cache when it has only recently been updated.
        # 1 hour
        cache_valid_time: 3600