- name: Install and configure Nginx on web servers  # Descriptive name for the playbook
  hosts: webserver                                  # Target group of servers from the inventory
  become: yes                                       # Use elevated privileges (e.g., sudo)
  tasks:                                            # List of tasks to execute

    - name: Copy and Execute the script 
      script: /home/host/Ansbile_new_project/Ansbile/UpdateUpgrade.sh

    # Task 1: Update the package cache
    #- name: Update apt cache                        # Descriptive name for the task
    #apt:                                          # Use the apt module (for Debian/Ubuntu systems)
    #   update_cache: yes                           # Refresh the package cache

    # Task 2: Install Nginx
    - name: Install Nginx                           # Descriptive name for installing Nginx
      apt:                                          # Use the apt module
        name: nginx                                 # Specify the package name to install
        state: present                              # Ensure the package is installed

    # Task 3: Start and enable the Nginx service
    - name: Ensure Nginx is running and enabled     # Descriptive name for service management
      service:                                      # Use the service module
        name: nginx                                 # Target the Nginx service
        state: started                              # Ensure the service is running
        enabled: true  



