# Add Docker's official GPG key:
# sudo apt-get update
# sudo apt-get install ca-certificates curl
# sudo install -m 0755 -d /etc/apt/keyrings
# sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
# sudo chmod a+r /etc/apt/keyrings/docker.asc

# # Add the repository to Apt sources:
# echo \
#   "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
#   $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
#   sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
# sudo apt-get update


# sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin



#to check docer is running
#sudo systemctl status docker


- name: Install and configure Nginx on web servers  # Descriptive name for the playbook
  hosts: webserver                                  # Target group of servers from the inventory
  become: yes                                       # Use elevated privileges (e.g., sudo)
  vars_files:
    - vars.yml
    
  tasks:                                            # List of tasks to execute

    - name: Update apt with specific options
      command:
        cmd: apt-get -o Acquire::Check-Valid-Until=false -o Acquire::Check-Date=false update

    - name: Update and upgrade all packages to the latest version
      apt:
        update_cache: true
        upgrade: dist
        cache_valid_time: 3600

   

    
    # Task 2: Install Nginx
    - name: Install Nginx                           # Descriptive name for installing Nginx
      apt:                                          # Use the apt module
        name: nginx                                 # Specify the package name to install
        state: present                              # Ensure the package is installed

    # Task 3: Start and enable the Nginx service
    - name: Ensure Nginx is running and enabled     # Descriptive name for service management
      service:                                      # Use the service module
        name: nginx                                 # Target the Nginx service
        state: started                              # Ensure the service is running
        enabled: true  


    # Task 1: Install prerequisite packages
   
    - name: Install prerequisite packages for docker
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - software-properties-common
        # Ensure Existence for present
        state: present

    # Task 2: Create directory for keyrings
    - name: Create directory for keyrings
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    # Task 3: Download Docker GPG key
    # - name: Download Docker GPG key
    #   get_url:
    #     url: https://download.docker.com/linux/ubuntu/gpg
    #     dest: /etc/apt/keyrings/docker.asc
    #     mode: '0644'

    - name: Add Docker's official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        keyring: /etc/apt/keyrings/docker.gpg
        state: present


    # - name: fix time
    #   command: sudo hwclock --hctosys 

     #temp solution for time zone 
    - name: Update apt with specific options
      command:
        cmd: apt-get -o Acquire::Check-Valid-Until=false -o Acquire::Check-Date=false update

  #Task 4: Add Docker repository
    - name: Add Docker repository
      apt_repository:
        repo: >-
          deb [arch=amd64
          signed-by=/etc/apt/keyrings/docker.gpg]
          https://download.docker.com/linux/ubuntu jammy stable
        filename: docker
        state: present

    # - name: Add Docker repository
    #   apt_repository:
    #     repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu jammy stable"
    #     filename: docker
    #     state: present

  

    - name: Update apt with specific options
      command:
        cmd: apt-get -o Acquire::Check-Valid-Until=false -o Acquire::Check-Date=false update

    # Task 5: Update apt package cache
    # sudo apt-get update
    - name: Update apt package cache
      apt:
        update_cache: yes

    # Task 6: Install Docker Engine and related components
    # sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
    - name: Install Docker Engine and related components
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present


    - name: Add user to Docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: true

    - name: Print user
      debug:
        msg: "user {{ansible_user}}"


    - name: Enable and start Docker services
      systemd:
        name: "{{ item }}"
        enabled: true
        state: started
      loop:
        - docker.service
        - containerd.service


   





