- name: Install and configure Nginx on web servers
  hosts: webserver
  become: yes
  vars_files:
    - vars.yml

  tasks:
    # Task 1: Update and upgrade all packages
    - name: Update and upgrade all packages to the latest version
      apt:
        update_cache: true
        upgrade: dist
        cache_valid_time: 3600
      ignore_errors: yes

    # Task 2: Update apt with specific options using `command`
    - name: Update apt with specific options
      command:
        cmd: apt-get -o Acquire::Check-Valid-Until=false -o Acquire::Check-Date=false update
      ignore_errors: yes

    # Task 3: Install Nginx
    - name: Install Nginx
      apt:
        name: nginx
        state: present

    # Task 4: Ensure Nginx is running and enabled
    - name: Ensure Nginx is running and enabled
      service:
        name: nginx
        state: started
        enabled: true

    # Task 5: Install prerequisite packages for Docker
    - name: Install prerequisite packages for Docker
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - software-properties-common
        state: present

    # Task 6: Create directory for keyrings
    - name: Create directory for keyrings
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    # Task 7: Add Docker's official GPG key
    - name: Add Docker's official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        keyring: /etc/apt/keyrings/docker.gpg
        state: present

    # Task 8: Add Docker repository
    - name: Add Docker repository
      apt_repository:
        repo: >-
          deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg]
          https://download.docker.com/linux/ubuntu jammy stable
        filename: docker
        state: present
      ignore_errors: yes

    # Task 9: Update apt cache again
    - name: Update apt package cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      ignore_errors: yes

    # Task 10: Install Docker Engine and related components
    - name: Install Docker Engine and related components
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    # Task 11: Add user to Docker group
    - name: Add user to Docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: true

    # Task 12: Enable and start Docker services
    - name: Enable and start Docker services
      systemd:
        name: "{{ item }}"
        enabled: true
        state: started
      loop:
        - docker.service
        - containerd.service
